import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { FormDataProvider } from "@/app/context/FormDataContext";
import { EmployeeProvider } from "@/app/context/EmployeeContext"; // Adicione o EmployeeProvider
import './globals.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FormDataProvider>
          <EmployeeProvider> {/* Certifique-se de que o EmployeeProvider engloba todos os componentes */}
            {children}
          </EmployeeProvider>
        </FormDataProvider>
      </body>
    </html>
  );
}
